version: '2'

services:
    web:
        build:
            context: ./images/margarita
            args:
                - REPOSADO_VERSION=${REPOSADO_VERSION}
                - MARGARITA_VERSION=${MARGARITA_VERSION}
        image: ianharrier/margarita:${MARGARITA_VERSION}
        restart: unless-stopped
        ports:
            - ${WEB_PORT}:80
        environment:
            - BASE_URL=${WEB_BASE_URL}
            - AUTH_TYPE=${AUTH_TYPE}
            - AUTH_AD_URL=${AUTH_AD_URL}
            - AUTH_AD_BIND_USER_DN=${AUTH_AD_BIND_USER_DN}
            - AUTH_AD_BIND_PASSWORD=${AUTH_AD_BIND_PASSWORD}
            - AUTH_AD_ALLOWED_GROUP_DN=${AUTH_AD_ALLOWED_GROUP_DN}
        volumes:
            - ./volumes/reposado/html:/srv/reposado/html
            - ./volumes/reposado/metadata:/srv/reposado/metadata
    sync:
        build:
            context: ./images/reposado
            args:
                - REPOSADO_VERSION=${REPOSADO_VERSION}
        image: ianharrier/reposado:${REPOSADO_VERSION}
        restart: unless-stopped
        environment:
            - BASE_URL=${WEB_BASE_URL}
            - SYNC_CRON_EXP=${SYNC_CRON_EXP}
            - PURGE_OPERATION=${PURGE_OPERATION}
            - PURGE_CRON_EXP=${PURGE_CRON_EXP}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/reposado/html:/srv/reposado/html
            - ./volumes/reposado/metadata:/srv/reposado/metadata
    backup:
        build:
            context: ./images/backup
            args:
                - GLIBC_VERSION=2.26-r0
                - COMPOSE_VERSION=1.17.1
        image: ianharrier/applesus-backup:1.0.9
        restart: unless-stopped
        environment:
            - OPERATION=${BACKUP_OPERATION}
            - CRON_EXP=${BACKUP_CRON_EXP}
            - RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./:${PWD}
            - /var/run/docker.sock:/var/run/docker.sock
