version: '2'

services:
    web:
        build:
            context: ./images/margarita
            args:
                - REPOSADO_VERSION=${REPOSADO_VERSION}
                - MARGARITA_VERSION=${MARGARITA_VERSION}
        image: ianharrier/margarita:${MARGARITA_VERSION}
        restart: unless-stopped
        ports:
            - ${WEB_PORT}:80
        environment:
            - BASE_URL=${WEB_BASE_URL}
            - AUTH_TYPE=${AUTH_TYPE}
            - AUTH_AD_URL=${AUTH_AD_URL}
            - AUTH_AD_BIND_USER_DN=${AUTH_AD_BIND_USER_DN}
            - AUTH_AD_BIND_PASSWORD=${AUTH_AD_BIND_PASSWORD}
            - AUTH_AD_ALLOWED_GROUP_DN=${AUTH_AD_ALLOWED_GROUP_DN}
        volumes:
            - ./volumes/reposado/html:/srv/reposado/html:z
            - ./volumes/reposado/metadata:/srv/reposado/metadata:z
    sync:
        build:
            context: ./images/reposado
            args:
                - REPOSADO_VERSION=${REPOSADO_VERSION}
        image: ianharrier/reposado:${REPOSADO_VERSION}
        restart: unless-stopped
        environment:
            - BASE_URL=${WEB_BASE_URL}
            - SYNC_CRON_EXP=${SYNC_CRON_EXP}
            - PURGE_OPERATION=${PURGE_OPERATION}
            - PURGE_CRON_EXP=${PURGE_CRON_EXP}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./volumes/reposado/html:/srv/reposado/html:z
            - ./volumes/reposado/metadata:/srv/reposado/metadata:z
    cron:
        build:
            context: ./images/cron
        image: ianharrier/applesus-cron:1.1.1
        restart: unless-stopped
        environment:
            - BACKUP_OPERATION=${BACKUP_OPERATION}
            - BACKUP_CRON_EXP=${BACKUP_CRON_EXP}
            - BACKUP_RETENTION=${BACKUP_RETENTION}
            - HOST_PATH=${PWD}
            - TIMEZONE=${TIMEZONE}
        volumes:
            - ./:${PWD}:z
